version: '2.3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.gpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: ubuntu:tsencoder
    runtime: nvidia
    container_name: tsencoder
    tty: true
    volumes:
        - ./app:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
